create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  game_id uuid not null,
  user_id uuid not null references public.users(id) on delete cascade,
  username text not null,
  category text not null,
  rank integer not null,
  item_name text not null,
  item_id text,
  total_score numeric(10,1) not null default 0,
  spent numeric(10,1) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists sessions_token_hash_idx on public.sessions(token_hash);
create index if not exists sessions_user_id_idx on public.sessions(user_id);
create index if not exists game_results_user_id_created_idx on public.game_results(user_id, created_at desc);
create index if not exists game_results_game_id_idx on public.game_results(game_id);

-- The Node.js server uses the Supabase service-role key, so it can access these tables securely.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in the browser or commit it to GitHub.
